### ISSUE TITLE
Issue related npm install

### ISSUE THREAD

**Issue by ghanshyamca** [kailashyogeshwar85/braille-loaders#1]
ghanshyam@ghanshyam-MS-7817:~/loader$ npm install --save braille-loader

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/braille-loader
npm ERR! 404 
npm ERR! 404 'braille-loader' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'loader'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by kailashyogeshwar85** [comment]
Resolved.
